// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiDxQJAmJOFV6ShL1tHjuG30o0fApsLTM',
    appId: '1:649211504330:web:a0216ed0327c5aa4daf633',
    messagingSenderId: '649211504330',
    projectId: 'servimarket-83d3a',
    authDomain: 'servimarket-83d3a.firebaseapp.com',
    storageBucket: 'servimarket-83d3a.firebasestorage.app',
    measurementId: 'G-43PS4QPR5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvy223ubdd6lX_LCBaSAQKwzgfsiyMXk',
    appId: '1:649211504330:android:6215a56773e611acdaf633',
    messagingSenderId: '649211504330',
    projectId: 'servimarket-83d3a',
    storageBucket: 'servimarket-83d3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzX2s71Gq16cpUuo_hCQ15QBriHaOTfC4',
    appId: '1:649211504330:ios:fc50d69124698454daf633',
    messagingSenderId: '649211504330',
    projectId: 'servimarket-83d3a',
    storageBucket: 'servimarket-83d3a.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzX2s71Gq16cpUuo_hCQ15QBriHaOTfC4',
    appId: '1:649211504330:ios:fc50d69124698454daf633',
    messagingSenderId: '649211504330',
    projectId: 'servimarket-83d3a',
    storageBucket: 'servimarket-83d3a.firebasestorage.app',
    iosBundleId: 'com.example.skillbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiDxQJAmJOFV6ShL1tHjuG30o0fApsLTM',
    appId: '1:649211504330:web:51da4549953ffa2fdaf633',
    messagingSenderId: '649211504330',
    projectId: 'servimarket-83d3a',
    authDomain: 'servimarket-83d3a.firebaseapp.com',
    storageBucket: 'servimarket-83d3a.firebasestorage.app',
    measurementId: 'G-5N4MCZBJ6J',
  );
}
